/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import modelo.Mascota;
import modelo.Tratamiento;

/**
 *
 * @author NEXO-MAX
 */
public class ViewAgregarConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewConsulta
     */
    public ViewAgregarConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        popupMenu1 = new java.awt.PopupMenu();
        cbMascota = new javax.swing.JComboBox<>();
        cbTratamiento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tConsulta = new javax.swing.JTable();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chActivo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        jLabel7.setText("CONSULTAS");

        popupMenu1.setLabel("popupMenu1");

        getContentPane().setLayout(null);

        getContentPane().add(cbMascota);
        cbMascota.setBounds(360, 130, 120, 20);

        getContentPane().add(cbTratamiento);
        cbTratamiento.setBounds(170, 210, 160, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("MASCOTA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 130, 70, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("TRATAMIENTOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 210, 96, 15);

        btnAgregar.setText("AGREGAR");
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(330, 280, 81, 23);

        tConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FECHA", "MASCOTA", "TRATAMIENTO", "PESO CONSULTA", "PRECIO"
            }
        ));
        jScrollPane3.setViewportView(tConsulta);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 360, 640, 70);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(450, 210, 81, 20);

        jLabel4.setText("PRECIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 210, 76, 23);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setText("Agregar consulta");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 40, 190, 29);
        getContentPane().add(chActivo);
        chActivo.setBounds(650, 210, 21, 21);

        jLabel1.setText("ACTIVO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 210, 46, 14);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(90, 180, 570, 10);

        btnCancelar.setText("CANCELAR");
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(450, 280, 85, 23);

        jLabel11.setText("FECHA");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 130, 50, 24);
        getContentPane().add(txtfecha);
        txtfecha.setBounds(120, 130, 86, 20);

        jLabel12.setText("PESO");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 130, 76, 23);
        getContentPane().add(txtPeso);
        txtPeso.setBounds(620, 130, 81, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(90, 320, 570, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-20, -50, 760, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Mascota> cbMascota;
    private javax.swing.JComboBox<Tratamiento> cbTratamiento;
    private javax.swing.JCheckBox chActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable tConsulta;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables
}
