/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import modelo.Cliente;
import modelo.Mascota;

/**
 *
 * @author Caro_Z
 */
public class ViewListadoConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewListadoConsulta
     */
    public ViewListadoConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setText("LISTA DE  CONSULTAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 70, 317, 24);

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(473, 171, 73, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 280, 577, 88);

        jRadioButton1.setText("avtivas");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(145, 220, 61, 23);

        jRadioButton2.setText("no Activas");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(316, 220, 75, 23);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(230, 130, 161, 20);

        jLabel2.setText("MASCOTA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(108, 131, 103, 14);

        jLabel3.setText("CLIENTE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(108, 175, 41, 14);

        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(230, 172, 161, 20);

        jButton2.setText("MODIFICAR");
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 420, 91, 23);

        jButton3.setText("DAR DE BAJA");
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 420, 97, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-50, -10, 760, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Mascota> jComboBox1;
    private javax.swing.JComboBox<Cliente> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
