/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ClienteData;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Conexion;

/**
 *
 * @author NEXO-MAX
 */
public class ViewCliente extends javax.swing.JInternalFrame {

    private ClienteData cliente;
    private Conexion conexion;

    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();
        limpiar();

        conexion = new Conexion();
        cliente = new ClienteData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< Updated upstream
=======
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
>>>>>>> Stashed changes
        jLabel4 = new javax.swing.JLabel();
        cId = new javax.swing.JTextField();
        cBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cCelular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        alternativo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cEstado = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
<<<<<<< Updated upstream
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cDNI = new javax.swing.JTextField();
        cGuardar = new javax.swing.JButton();
        cBorrar = new javax.swing.JButton();
        cActualizar = new javax.swing.JButton();
        cLimpiar = new javax.swing.JButton();
        cSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);
=======
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 260, 30));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 160, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 610, 10));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 60, 30));
>>>>>>> Stashed changes

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID Cliente:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 150, 87, 23);

        cId.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cId);
        cId.setBounds(180, 140, 60, 30);

        cBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cBuscar.setForeground(new java.awt.Color(0, 0, 0));
        cBuscar.setText("Buscar ");
        cBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(cBuscar);
        cBuscar.setBounds(260, 140, 90, 29);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Ingresar cliente");
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 170, 140, 29);

        cApellido.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cApellido);
        cApellido.setBounds(180, 280, 160, 30);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellido:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 290, 75, 23);

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 330, 72, 23);

        cNombre.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cNombre);
        cNombre.setBounds(180, 320, 160, 30);

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Dirección:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 370, 81, 23);

        cDireccion.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cDireccion);
        cDireccion.setBounds(180, 360, 260, 30);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Celular:");
<<<<<<< Updated upstream
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 410, 64, 23);
=======
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));
>>>>>>> Stashed changes

        cCelular.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cCelular);
        cCelular.setBounds(180, 400, 260, 30);

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nomb. Contacto:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 440, 138, 23);

        alternativo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alternativo);
        alternativo.setBounds(230, 440, 210, 30);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estado:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 480, 60, 23);

        cEstado.setBackground(new java.awt.Color(255, 255, 255));
        cEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(cEstado);
        cEstado.setBounds(180, 480, 21, 21);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(80, 210, 360, 10);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Clientes");
<<<<<<< Updated upstream
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 30, 150, 48);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Buscar cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(550, 130, 140, 29);

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DNI:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 250, 40, 23);

        cDNI.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cDNI);
        cDNI.setBounds(180, 240, 160, 30);

        cGuardar.setBackground(new java.awt.Color(255, 255, 255));
        cGuardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cGuardar.setForeground(new java.awt.Color(0, 0, 0));
        cGuardar.setText("Guardar");
        cGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(cGuardar);
        cGuardar.setBounds(80, 560, 100, 29);

        cBorrar.setBackground(new java.awt.Color(255, 255, 255));
        cBorrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cBorrar.setForeground(new java.awt.Color(0, 0, 0));
        cBorrar.setText("Borrar");
        cBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cBorrar);
        cBorrar.setBounds(210, 560, 100, 29);

        cActualizar.setBackground(new java.awt.Color(255, 255, 255));
        cActualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cActualizar.setForeground(new java.awt.Color(0, 0, 0));
        cActualizar.setText("Actualizar");
        cActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(cActualizar);
        cActualizar.setBounds(340, 560, 100, 29);

        cLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        cLimpiar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        cLimpiar.setText("Limpiar");
        cLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(cLimpiar);
        cLimpiar.setBounds(470, 560, 100, 29);

        cSalir.setBackground(new java.awt.Color(255, 255, 255));
        cSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cSalir.setForeground(new java.awt.Color(0, 0, 0));
        cSalir.setText("Salir");
        cSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSalirActionPerformed(evt);
            }
        });
        getContentPane().add(cSalir);
        cSalir.setBounds(600, 560, 90, 29);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(80, 530, 610, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 630);
=======
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 186, -1, -1));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 790, 710));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 786, 700);
>>>>>>> Stashed changes

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cEstadoActionPerformed

    private void cGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cGuardarActionPerformed
        int dni = Integer.parseInt(cDNI.getText());
        String apellido = cApellido.getText();
        String nombre = cNombre.getText();
        String direccion = cDireccion.getText();
        int celular = Integer.parseInt(cCelular.getText());
        String alt = alternativo.getText();
        boolean estado = cEstado.isEnabled();

        Cliente c = new Cliente(dni, apellido, nombre, direccion, celular, alt, estado);

        cliente.agregarCliente(c);
        cId.setText(c.getIdCliente() + "");
        limpiar();

    }//GEN-LAST:event_cGuardarActionPerformed

    private void cBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBorrarActionPerformed
        int id = Integer.parseInt(cId.getText());
        if (cliente.clienteExiste(id)) {
            cliente.eliminarCliente(id);
            limpiar();
            desactivarOtros();
            desactivarId();
        } else {
            JOptionPane.showMessageDialog(this, "El clinete no existe");
        }
    }//GEN-LAST:event_cBorrarActionPerformed

    private void cActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActualizarActionPerformed
        if (cId.getText() != null) {
            int id = Integer.parseInt(cId.getText());
            int dni = Integer.parseInt(cDNI.getText());
            String apellido = cApellido.getText();
            String nombre = cNombre.getText();
            String direccion = cDireccion.getText();
            int celular = Integer.parseInt(cCelular.getText());
            String alt = alternativo.getText();
            boolean estado = cEstado.isEnabled();

            Cliente c = new Cliente(dni, apellido, nombre, direccion, celular, alt, estado);
            cliente.modificarCliente(id, c);

            JOptionPane.showMessageDialog(null, "Cliente modificado con exito");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo modificar el cliente");
        }
    }//GEN-LAST:event_cActualizarActionPerformed

    private void cLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_cLimpiarActionPerformed

    private void cBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBuscarActionPerformed
        botonesBuscar();
        activarOtros();

        Cliente c = cliente.buscarCliente(Integer.parseInt(cId.getText()));

        int id = Integer.parseInt(cId.getText());

        if (cId.getText() != null && cliente.clienteExiste(id)) {
 
            int dni = Integer.parseInt(cId.getText());
            cApellido.setText(c.getApellido());
            cNombre.setText(c.getNombre());
            cDireccion.setText(c.getDireccion());
            int cel = Integer.parseInt(cId.getText());
            alternativo.setText(c.getContactoAlternativo());
            cEstado.setSelected(c.isActivo());
            desactivarOtros();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el cliente");
        }

        activarOtros();
    }//GEN-LAST:event_cBuscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSalirActionPerformed
        dispose();
    }//GEN-LAST:event_cSalirActionPerformed
    private void limpiar() {
        cId.setText("");
        cDNI.setText("");
        cApellido.setText("");
        cNombre.setText("");
        cDireccion.setText("");
        cCelular.setText("");
        alternativo.setText("");
        cEstado.setSelected(false);
        desactivarOtros();
        desactivarId();
        botonesDesactivados();

    }

    private void activarId() {
        cId.setEnabled(true);
    }

    private void desactivarId() {
        cId.setEnabled(false);
    }

    private void activarOtros() {
        cNombre.setEnabled(true);
        cApellido.setEnabled(true);

    }

    private void desactivarOtros() {
        cNombre.setEnabled(false);
        cApellido.setEnabled(false);
        cEstado.setEnabled(false);
    }

    private void botonesDesactivados() {
        cGuardar.setEnabled(false);
        cBorrar.setEnabled(false);
        cActualizar.setEnabled(false);
        cBuscar.setEnabled(false);
    }

    private void botonesBuscar() {
        cActualizar.setEnabled(true);
        cBorrar.setEnabled(true);
    }

    private void sinBotonesBuscar() {
        cActualizar.setEnabled(false);
        cBorrar.setEnabled(false);
    }

    private void botonesGuardar() {
        cGuardar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alternativo;
    private javax.swing.JButton cActualizar;
    private javax.swing.JTextField cApellido;
    private javax.swing.JButton cBorrar;
    private javax.swing.JButton cBuscar;
    private javax.swing.JTextField cCelular;
    private javax.swing.JTextField cDNI;
    private javax.swing.JTextField cDireccion;
    private javax.swing.JCheckBox cEstado;
    private javax.swing.JButton cGuardar;
    private javax.swing.JTextField cId;
    private javax.swing.JButton cLimpiar;
    private javax.swing.JTextField cNombre;
    private javax.swing.JButton cSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
<<<<<<< Updated upstream
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
=======
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
>>>>>>> Stashed changes
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
