/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import controlador.ConsultaData;
import controlador.TratamientoData;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Conexion;
import modelo.Tratamiento;

/**
 *
 * @author Manuel Belgrano Nº3
 */
public class ViewTratamiento extends javax.swing.JInternalFrame {

   private TratamientoData tratamientoData;
    private Conexion conexion;

    public ViewTratamiento() {
        initComponents();
        this.setSize(720, 630);
        conexion = new Conexion();
        
        tratamientoData = new TratamientoData(conexion);
        cargartipoTratamiento();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbActivo = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tDescrip = new javax.swing.JTextField();
        tMedicamento = new javax.swing.JTextField();
        tPrecio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        tId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbTipo1 = new javax.swing.JComboBox<>();

        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Agregar tratamiento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 30, 340, 48);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(40, 450, 610, 10);

        cbActivo.setBackground(new java.awt.Color(255, 255, 255));
        cbActivo.setEnabled(false);
        cbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActivoActionPerformed(evt);
            }
        });
        getContentPane().add(cbActivo);
        cbActivo.setBounds(320, 410, 21, 21);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel7.setText("Activo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 410, 58, 23);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel10.setText("Precio: $");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 370, 80, 23);

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel9.setText("Medicamento:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 330, 140, 23);

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel6.setText("Descripción:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 290, 100, 23);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel5.setText("Tipo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 120, 42, 23);

        tDescrip.setEnabled(false);
        tDescrip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tDescripFocusLost(evt);
            }
        });
        tDescrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescripActionPerformed(evt);
            }
        });
        tDescrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tDescripKeyTyped(evt);
            }
        });
        getContentPane().add(tDescrip);
        tDescrip.setBounds(320, 280, 260, 30);

        tMedicamento.setEnabled(false);
        tMedicamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tMedicamentoFocusLost(evt);
            }
        });
        tMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMedicamentoActionPerformed(evt);
            }
        });
        getContentPane().add(tMedicamento);
        tMedicamento.setBounds(320, 320, 260, 30);

        tPrecio.setEnabled(false);
        tPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPrecioFocusLost(evt);
            }
        });
        tPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecioActionPerformed(evt);
            }
        });
        tPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(tPrecio);
        tPrecio.setBounds(320, 360, 110, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(70, 210, 470, 10);

        tId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tIdFocusLost(evt);
            }
        });
        tId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdActionPerformed(evt);
            }
        });
        tId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tIdKeyTyped(evt);
            }
        });
        getContentPane().add(tId);
        tId.setBounds(230, 160, 60, 20);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel4.setText("ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 160, 30, 23);

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnIngresar.setText("Ingresar ");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(40, 230, 90, 40);

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(40, 500, 110, 27);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(580, 500, 110, 27);

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar ");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(480, 147, 90, 40);

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(180, 500, 110, 27);

        cbTipo.setEnabled(false);
        getContentPane().add(cbTipo);
        cbTipo.setBounds(230, 120, 210, 20);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(320, 500, 110, 30);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(460, 500, 100, 30);

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel8.setText("Tipo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 250, 42, 23);

        cbTipo1.setEnabled(false);
        getContentPane().add(cbTipo1);
        cbTipo1.setBounds(320, 250, 260, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActivoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       if (tId.getText().isEmpty()){
          JOptionPane.showMessageDialog(this, "Debe ingrear un ID"); 
       }
        
        
        
        
        Tratamiento t = tratamientoData.buscarTratamiento(Integer.parseInt(tId.getText()));

        int id = Integer.parseInt(tId.getText());

        if (tId.getText() != null && tratamientoData.tratamientoExiste(id)) {

            cbTipo.setSelectedItem(t.getTipoTratamiento()); ///
            
            tDescrip.setText(t.getDescripcion() );
            tMedicamento.setText(t.getMedicamento());
            tPrecio.setText(t.getPrecio()+ "");
            cbActivo.setSelected(t.isActivo());//
            
       

            btnGuardar.setEnabled(false);
            activarCampos();
            cbActivo.setEnabled(false);
            
            btnModificar.setEnabled(true);
        } else {

            JOptionPane.showMessageDialog(this, "El tratamiento no existe");
            desactivarCampos();
            desactivarBtnSec();

        }
        if (cbActivo.isSelected()) {//
            btnEliminar.setEnabled(true);
            btnModificar.setEnabled(true);
        }else{
             btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);
            desactivarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       btnBuscar.setEnabled(false);
        tId.setEnabled(false);
        tId.setText("");
        cbTipo.setEnabled(true);
        tDescrip.setEnabled(true);
        tMedicamento.setEnabled(true);
        tPrecio.setEnabled(true);
        cbActivo.setEnabled(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
       Tratamiento t = (Tratamiento) cbTipo.getSelectedItem();
 
        String descripcion = tDescrip.getText();
        String medicamento =tMedicamento.getText();
        double precio = Double.parseDouble(tPrecio.getText());
       
         cbActivo.isSelected();
          if (cbActivo.isSelected() && !tDescrip.getText().isEmpty()&& !tMedicamento.getText().isEmpty() && !tPrecio.getText().isEmpty() ){
              
          
        Tratamiento tr = new Tratamiento(t.getTipoTratamiento(), descripcion,medicamento,precio, cbActivo.isSelected());
  
         
              if (cbActivo.isSelected())  {//
              
            tratamientoData.agregarTratamiento(tr);
            tId.setText(tr.getIdTratamiento() + "");
            desactivarCampos();
        } else {
            JOptionPane.showMessageDialog(this, " Esta agregando un tratamiento con estado inactivo");//
            cbActivo.isFocusPainted();//
        }
          }  cbActivo.setSelected(true);//
          limpiarCampos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       
        if ((tId.getText() != null)) {
            int id = Integer.parseInt(tId.getText());
            
            Tratamiento t = (Tratamiento) cbTipo.getSelectedItem();
     
        String descripcion = tDescrip.getText();
        String medicamento =tMedicamento.getText();
        double precio = Double.parseDouble(tPrecio.getText());
        
        cbActivo.setEnabled(false);
        cbActivo.setSelected(true);
            
       Tratamiento tr= new  Tratamiento(t.getTipoTratamiento(),descripcion,medicamento,precio,cbActivo.isSelected()  );
            
       tratamientoData.modificarTratamiento(id, tr);
         desactivarCampos();   
           
       btnGuardar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "El tratamiento no se encuentra activo");
       }limpiarCampos();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tDescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescripActionPerformed

    private void tMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMedicamentoActionPerformed

    private void tPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            tId.setText("");
            tDescrip.setText("");
            tMedicamento.setText("");
            tPrecio.setText("");
            cbActivo.setSelected(false);
            
            tId.setEnabled(true);
            
            desactivarCampos();
            desactivarBtnSec();
            
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id = Integer.parseInt(tId.getText());

       
        if (tId.getText() != null)
        {
            tratamientoData.eliminarTratamiento(id);
            btnGuardar.setEnabled(false);
            btnModificar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, " Debe ingresar un id ");
        }
        desactivarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdActionPerformed
      
    }//GEN-LAST:event_tIdActionPerformed

    private void tIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdKeyTyped
         int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
       
        if (!numeros  ) {
            JOptionPane.showMessageDialog(this, "El id debe ser numérico");
            evt.consume();
        }
    }//GEN-LAST:event_tIdKeyTyped

    private void tPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPrecioKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean coma = key ==44 ;
        boolean punto=key ==46;
        if (!(numeros ||coma || punto) )
        {
            JOptionPane.showMessageDialog(this, "Ingrese un precio válido");
            evt.consume();
        }
    }//GEN-LAST:event_tPrecioKeyTyped

    private void tDescripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDescripKeyTyped
       int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
//            JOptionPane.showMessageDialog(this, "Ingrese un nombre válido");
            evt.consume();
        }
    }//GEN-LAST:event_tDescripKeyTyped

    private void tMedicamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tMedicamentoFocusLost
        if (tMedicamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Medicamento debe estar completo");
            tMedicamento.requestFocus();
        }
    }//GEN-LAST:event_tMedicamentoFocusLost

    private void tIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tIdFocusLost
        if (tId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Para buscar debe ingresar un ID");
            requestFocus();
            btnBuscar.setEnabled(false);
        }
        btnBuscar.setEnabled(true);
    }//GEN-LAST:event_tIdFocusLost

    private void tPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPrecioFocusLost
         if (tPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo precio debe estar completo");
            tPrecio.requestFocus();
        } else {
            btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_tPrecioFocusLost

    private void tDescripFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDescripFocusLost
         if (tDescrip.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo descripción debe estar completo");
            tDescrip.requestFocus();
        }
    }//GEN-LAST:event_tDescripFocusLost
    
    private void desactivarCampos(){
            cbTipo.setEnabled(false);
            tDescrip.setEnabled(false);
            tMedicamento.setEnabled(false);
            tPrecio.setEnabled(false);
            cbActivo.setEnabled(false);
    }
    private void activarCampos(){
            cbTipo.setEnabled(true);
            tDescrip.setEnabled(true);
            tMedicamento.setEnabled(true);
            tPrecio.setEnabled(true);
            cbActivo.setEnabled(true);
    }
    
    private void ActivarBtnSec(){
            btnEliminar.setEnabled(true);
            btnModificar.setEnabled(true);
            btnGuardar.setEnabled(true);
    }
    
    
    private void desactivarBtnSec(){
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnGuardar.setEnabled(false);
    }
    private void limpiarCampos(){
            
         
            tDescrip.setText("");
            tMedicamento.setText("");
            tPrecio.setText("");
            cbActivo.setSelected(false);
            tId.setEnabled(true);//
       
    }
    
 
    private void cargartipoTratamiento() {
   
       List<Tratamiento>  listaTiposTrat = tratamientoData.listarTratamientosActivos();
     
               for (Tratamiento item : listaTiposTrat) {
                   
            cbTipo.addItem(item);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbActivo;
    private javax.swing.JComboBox<Tratamiento> cbTipo;
    private javax.swing.JComboBox<Tratamiento> cbTipo1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tDescrip;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tMedicamento;
    private javax.swing.JTextField tPrecio;
    // End of variables declaration//GEN-END:variables

}
