/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ClienteData;
import controlador.ConsultaData;
import controlador.MascotaData;
import controlador.TratamientoData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Conexion;
import modelo.Consulta;
import modelo.Mascota;
import modelo.TablaModelo;
import modelo.Tratamiento;

/**
 *
 * @author NEXO-MAX
 */
public class ViewGestionConsulta extends javax.swing.JInternalFrame {

    private ArrayList<Tratamiento> tratamientos;
    private TratamientoData tData;
    private ArrayList<Consulta> consultas;
    private ConsultaData cData;
    private ArrayList<Mascota> mascotas;
    private MascotaData mData;
    private ArrayList<Cliente> clientes;
    private ClienteData clienteData;
    private Conexion conexion;
    private DefaultTableModel modelo;

    public ViewGestionConsulta() {
        initComponents();
        try {
            conexion = new Conexion();
            cData = new ConsultaData(conexion);

            tData = new TratamientoData(conexion);
            tratamientos = (ArrayList<Tratamiento>) tData.listarTratamientos(0,null);

            mData = new MascotaData(conexion);
            mascotas = (ArrayList<Mascota>) mData.listarMascotasActivas();
            modelo = new DefaultTableModel();

            cargarTratamiento();
            cargarMascota();
          
            cargarTabla(0, null);
            
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        popupMenu1 = new java.awt.PopupMenu();
        jScrollBar1 = new javax.swing.JScrollBar();
        cbMascota = new javax.swing.JComboBox<>();
        cbTratamiento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tConsulta = new javax.swing.JTable();
        tPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chActivo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tPeso = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        tFecha = new com.toedter.calendar.JDateChooser();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rActiva = new javax.swing.JRadioButton();
        rNoActiva = new javax.swing.JRadioButton();
        rTodos = new javax.swing.JRadioButton();
        cFiltro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tFiltro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        cbMascota1 = new javax.swing.JComboBox<>();
        cbTratamiento1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tConsulta1 = new javax.swing.JTable();
        tPrecio1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        chActivo1 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnSalir1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tPeso1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        tFecha1 = new com.toedter.calendar.JDateChooser();
        btnLimpiar1 = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        cFiltro1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        tFiltro1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnConsultar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        jLabel7.setText("CONSULTAS");

        popupMenu1.setLabel("popupMenu1");

        setBorder(null);
        getContentPane().setLayout(null);

        getContentPane().add(cbMascota);
        cbMascota.setBounds(559, 186, 248, 20);

        getContentPane().add(cbTratamiento);
        cbTratamiento.setBounds(559, 230, 248, 20);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel2.setText("Mascota:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(431, 186, 90, 23);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel3.setText("Tratamiento:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(431, 227, 103, 23);

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(431, 459, 71, 23);

        tConsulta.setBackground(new java.awt.Color(204, 255, 204));
        tConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FECHA", "MASCOTA", "TRATAMIENTO", "PESO CONSULTA", "PRECIO"
            }
        ));
        jScrollPane3.setViewportView(tConsulta);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 352, 388, 177);

        tPrecio.setEnabled(false);
        tPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPrecioFocusLost(evt);
            }
        });
        tPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecioActionPerformed(evt);
            }
        });
        tPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(tPrecio);
        tPrecio.setBounds(559, 315, 248, 20);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(431, 312, 76, 23);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("Gestionar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(580, 100, 118, 29);

        chActivo.setSelected(true);
        chActivo.setEnabled(false);
        getContentPane().add(chActivo);
        chActivo.setBounds(559, 341, 30, 21);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel1.setText("Activo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(431, 341, 65, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(40, 150, 288, 10);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(713, 459, 78, 23);

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel11.setText("Fecha:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(431, 147, 90, 30);

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel12.setText("Peso:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(431, 283, 76, 23);

        tPeso.setEnabled(false);
        tPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPesoFocusLost(evt);
            }
        });
        tPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tPesoKeyTyped(evt);
            }
        });
        getContentPane().add(tPeso);
        tPeso.setBounds(559, 286, 248, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 332, 368, 2);

        tFecha.setBackground(new java.awt.Color(153, 204, 255));
        tFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFechaFocusLost(evt);
            }
        });
        tFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFechaMouseClicked(evt);
            }
        });
        getContentPane().add(tFecha);
        tFecha.setBounds(559, 147, 110, 20);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(613, 459, 82, 23);

        btnModificar.setText("Modificar");
        getContentPane().add(btnModificar);
        btnModificar.setBounds(520, 459, 75, 23);

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setText("Listado de consultas");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 110, 269, 36);

        rActiva.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        rActiva.setText("Activas");
        rActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActivaActionPerformed(evt);
            }
        });
        getContentPane().add(rActiva);
        rActiva.setBounds(285, 185, 73, 25);

        rNoActiva.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        rNoActiva.setText("No Activas");
        rNoActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNoActivaActionPerformed(evt);
            }
        });
        getContentPane().add(rNoActiva);
        rNoActiva.setBounds(156, 185, 97, 25);

        rTodos.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        rTodos.setText("Todas");
        rTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTodosActionPerformed(evt);
            }
        });
        getContentPane().add(rTodos);
        rTodos.setBounds(38, 185, 65, 25);

        cFiltro.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        cFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "apellido", "alias", "tipoTratamiento" }));
        getContentPane().add(cFiltro);
        cFiltro.setBounds(150, 220, 227, 23);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel5.setText("Filtrar Por:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 220, 85, 17);

        tFiltro.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        getContentPane().add(tFiltro);
        tFiltro.setBounds(150, 260, 227, 23);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel10.setText("Ingresar dato:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 260, 105, 17);

        jButton1.setText("Promediar");
        getContentPane().add(jButton1);
        jButton1.setBounds(713, 393, 81, 23);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(582, 394, 109, 20);

        btnAlta.setText("Dar de Allta");
        getContentPane().add(btnAlta);
        btnAlta.setBounds(281, 303, 89, 23);

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel13.setText("Promediar peso:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(431, 391, 133, 23);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(420, 140, 368, 11);

        btnBuscar.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(45, 301, 75, 25);

        jInternalFrame1.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel14.setText("Mascota:");

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel15.setText("Tratamiento:");

        btnGuardar1.setText("Guardar");
        btnGuardar1.setEnabled(false);
        btnGuardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardar1MouseClicked(evt);
            }
        });
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        tConsulta1.setBackground(new java.awt.Color(204, 255, 204));
        tConsulta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tConsulta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tConsulta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FECHA", "MASCOTA", "TRATAMIENTO", "PESO CONSULTA", "PRECIO"
            }
        ));
        jScrollPane4.setViewportView(tConsulta1);

        tPrecio1.setEnabled(false);
        tPrecio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPrecio1FocusLost(evt);
            }
        });
        tPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecio1ActionPerformed(evt);
            }
        });
        tPrecio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tPrecio1KeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel16.setText("Precio:");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 204));
        jLabel17.setText("Gestionar");

        chActivo1.setSelected(true);
        chActivo1.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel18.setText("Activo:");

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel19.setText("Fecha:");

        jLabel20.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel20.setText("Peso:");

        tPeso1.setEnabled(false);
        tPeso1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPeso1FocusLost(evt);
            }
        });
        tPeso1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tPeso1KeyTyped(evt);
            }
        });

        tFecha1.setBackground(new java.awt.Color(153, 204, 255));
        tFecha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFecha1FocusLost(evt);
            }
        });
        tFecha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFecha1MouseClicked(evt);
            }
        });

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        btnModificar1.setText("Modificar");

        jLabel21.setFont(new java.awt.Font("Leelawadee UI", 0, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 204));
        jLabel21.setText("Listado de consultas");

        jRadioButton4.setText("Activas");

        jRadioButton5.setText("No Activas");

        jRadioButton6.setText("Todas");

        cFiltro1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apellido Cliente", "Alias Mascota", "Tipo Tratamiento" }));

        jLabel22.setText("Filtrar Por:");

        jLabel23.setText("Ingresar dato:");

        jButton4.setText("Promediar");

        jButton5.setText("Dar de Allta");

        jLabel24.setText("Promediar peso:");

        jButton6.setText("Buscar");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jRadioButton6)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton5)
                                        .addGap(57, 57, 57)
                                        .addComponent(jRadioButton4))
                                    .addComponent(cFiltro1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tFiltro1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(42, 42, 42)))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jButton6))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(btnGuardar1)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar1)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                                .addGap(25, 25, 25)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chActivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPeso1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(tPrecio1)
                                    .addComponent(cbMascota1, 0, 248, Short.MAX_VALUE)
                                    .addComponent(cbTratamiento1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                    .addGap(129, 129, 129)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jButton5)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(cbMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cbTratamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel23))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton6)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton5)
                                        .addComponent(jRadioButton4)))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(cFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chActivo1)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(83, 83, 83)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar1)
                            .addComponent(btnGuardar1)
                            .addComponent(btnLimpiar1)
                            .addComponent(btnSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(420, 276, 0, 0);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(431, 375, 360, 5);

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(320, 100, 93, 23);

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(430, 100, 83, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPesoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean coma = key == 44;
        boolean punto = key == 46;
        if (!(numeros || coma || punto)) {
//            JOptionPane.showMessageDialog(this, "Ingrese un peso válido");
            evt.consume();
        }
    }//GEN-LAST:event_tPesoKeyTyped

    private void tFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFechaMouseClicked
        // TODO add your handling code here:
        if (tFecha.isDisplayable() && tFecha.getAutoscrolls()) {

            btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_tFechaMouseClicked

    private void tFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFechaFocusLost
        
        if (null == tFecha.getDate()) {
            JOptionPane.showMessageDialog(this, "No puede dejar vacio este campo");
            tFecha.requestFocus();
            btnGuardar.setEnabled(false);
        } else {
            btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_tFechaFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 String a = null;
        if (controlar()) {
            registrar();
            cargarTabla(0,null);
        } else {
            desactivarCampos();
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        tPrecio.setText("");
        tPeso.setText("");
        tFecha.setDate(null);

        btnGuardar.setEnabled(false);


    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPrecioKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean coma = key == 44;
        boolean punto = key == 46;
        if (!(numeros || coma || punto)) {
//            JOptionPane.showMessageDialog(this, "Ingrese un peso válido");
            evt.consume();
        }
    }//GEN-LAST:event_tPrecioKeyTyped

    private void tPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecioActionPerformed

    }//GEN-LAST:event_tPrecioActionPerformed

    private void tPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPrecioFocusLost
        // TODO add your handling code here:
        if (tFecha.getDate() != null) {

            if (!tPeso.getText().isEmpty()) { //

                if (!tPrecio.getText().isEmpty()) {

                    btnGuardar.setEnabled(true);

                } else {
                    JOptionPane.showMessageDialog(this, "No puede dejar campos vacíos ");
                    tPrecio.requestFocus();

                }
            }

        }


    }//GEN-LAST:event_tPrecioFocusLost

    private void tPesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPesoFocusLost
        if (tPeso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo peso debe estar completo");
            tPeso.requestFocus();

        }
    }//GEN-LAST:event_tPesoFocusLost

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
 String a = null;
        if (controlar()) {
            registrar();
            cargarTabla(0,null);
        } else {

        }


    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1MouseClicked

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void tPrecio1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPrecio1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecio1FocusLost

    private void tPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecio1ActionPerformed

    private void tPrecio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPrecio1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecio1KeyTyped

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void tPeso1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPeso1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tPeso1FocusLost

    private void tPeso1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPeso1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tPeso1KeyTyped

    private void tFecha1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFecha1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tFecha1FocusLost

    private void tFecha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFecha1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tFecha1MouseClicked

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       filtrarTipo();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActivaActionPerformed
       String c = null;
        cargarTabla(2,null);
    }//GEN-LAST:event_rActivaActionPerformed

    private void rNoActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNoActivaActionPerformed
       String b = null;
        cargarTabla(1,null);
    }//GEN-LAST:event_rNoActivaActionPerformed

    private void rTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTodosActionPerformed
      String a = null;
        cargarTabla(0,null);
    }//GEN-LAST:event_rTodosActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       activarCampos();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
       desactivarCampos();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void cargarTratamiento() {

        for (Tratamiento item : tratamientos) {

            cbTratamiento.addItem(item);

        }

    }

    private void cargarMascota() {

        for (Mascota item : mascotas) {

            cbMascota.addItem(item);

        }

    }



    private void borraFilasTabla() {

        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }

    private boolean controlar() {
        boolean control = false;
        if (tFecha.getDate() == null) {

            if (tPeso.getText().isEmpty()) { //

                if (tPrecio.getText().isEmpty()) {

                    JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos");
                }
            }
        }
        return control;
    }

    private void registrar() {

        double precio = Double.parseDouble(tPrecio.getText());
        Date fech = tFecha.getDate();
        LocalDate fechaNac = fech.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Mascota seleccionada = (Mascota) cbMascota.getSelectedItem();
        Tratamiento seleccionado = (Tratamiento) cbTratamiento.getSelectedItem();
        boolean estado = chActivo.isSelected();
        double PesoC = Double.parseDouble(tPeso.getText());
        Consulta consul = new Consulta(precio, fechaNac, seleccionada, seleccionado, estado, PesoC);
    try{
        if (chActivo.isSelected() && !tPrecio.getText().isEmpty() && tFecha.getDate() != null && !tPeso.getText().isEmpty()) {
            cData.registrarConsulta(consul);
        } else {

            JOptionPane.showMessageDialog(this, " Esta agregando una consulta con estado inactivo");//
            chActivo.isFocusPainted();//
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
     }
        
        chActivo.setSelected(true);//

       // modelo.addRow(new Object[]{consul.getIdConsulta(), consul.getFechaConsulta(), consul.getMascota().getAlias(), consul.getTratamiento().getTipoTratamiento(), consul.getPesoConsulta(), consul.getPrecio()});
    }

    private void desactivarCampos() {
        tPrecio.setEnabled(false);
        tFecha.setEnabled(false);
        cbMascota.setEnabled(false);
        cbTratamiento.setEnabled(false);
        chActivo.setEnabled(false);
        tPeso.setEnabled(false);
    }

    private void activarCampos() {
        tPrecio.setEnabled(true);
        tFecha.setEnabled(true);
        cbMascota.setEnabled(true);
        cbTratamiento.setEnabled(true);
        chActivo.setEnabled(true);
        tPeso.setEnabled(true);
    }

    private void tablaConsultas(int filas) {
        String titulos[] = new String[7];
        titulos[0] = "ID";
        titulos[1] = "FECHA";
        titulos[2] = "MASCOTA";
        titulos[3] = "CLIENTE";
        titulos[4] = "PESO CONSULTA";
        titulos[5] = "PRECIO";
        titulos[6] = "ACTIVO";

        tConsulta.setModel(new TablaModelo(titulos, filas));

    }

    private void cargarTabla(int valor, String s) {
        consultas = new ArrayList<Consulta>();
        consultas = cData.listarConsultas(valor, s);
        tablaConsultas(consultas.size());
        if (!consultas.isEmpty()) {
            for (int i = 0; i < consultas.size(); i++) {

                tConsulta.setValueAt(consultas.get(i).getIdConsulta(), i, 0);
                tConsulta.setValueAt(consultas.get(i).getFechaConsulta(), i, 1);
                tConsulta.setValueAt(consultas.get(i).getMascota().getAlias(), i, 2);
               tConsulta.setValueAt(consultas.get(i).getMascota().getCliente().getApellido(), i, 3);
                tConsulta.setValueAt(consultas.get(i).getPesoConsulta(), i, 4);
                tConsulta.setValueAt(consultas.get(i).getPrecio(), i, 5);
                tConsulta.setValueAt(consultas.get(i).isActivo(), i, 6);
                if (consultas.get(i).isActivo()) {
                    tConsulta.setValueAt("Si", i, 6);
                } else {
                    tConsulta.setValueAt("No", i, 6);
                }
            }
        }

    }
    
     private void filtrarTipo() {
         
         String valor=tFiltro.getText();    
       int campo=Integer.parseInt((String) cFiltro.getSelectedItem());
         
         ArrayList<Consulta>consultas=cData.listarConsultas(campo, valor);
       
         tablaConsultas(consultas.size());  
           cargarTabla(campo,valor); 
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cFiltro;
    private javax.swing.JComboBox<String> cFiltro1;
    private javax.swing.JComboBox<Mascota> cbMascota;
    private javax.swing.JComboBox<Mascota> cbMascota1;
    private javax.swing.JComboBox<Tratamiento> cbTratamiento;
    private javax.swing.JComboBox<Tratamiento> cbTratamiento1;
    private javax.swing.JCheckBox chActivo;
    private javax.swing.JCheckBox chActivo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JRadioButton rActiva;
    private javax.swing.JRadioButton rNoActiva;
    private javax.swing.JRadioButton rTodos;
    private javax.swing.JTable tConsulta;
    private javax.swing.JTable tConsulta1;
    private com.toedter.calendar.JDateChooser tFecha;
    private com.toedter.calendar.JDateChooser tFecha1;
    private javax.swing.JTextField tFiltro;
    private javax.swing.JTextField tFiltro1;
    private javax.swing.JTextField tPeso;
    private javax.swing.JTextField tPeso1;
    private javax.swing.JTextField tPrecio;
    private javax.swing.JTextField tPrecio1;
    // End of variables declaration//GEN-END:variables
}
